[project]
name = "cvrpnotebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.19.11",
    "uniformcvrpdemo>=0.1.2",
]
